account_app/urls.py
from django.urls import path
from account_app import views

app_name = 'account_app'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile')
]

commandments_app/urls.py
from django.urls import path
from commandments_app import views

app_name = 'commandments_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('homepage/', views.homepage, name='homepage'),
    path('all_commandments/', views.all_commandments, name='all_commandments'),
    path('commandments_filtering/', views.CommandmentsFiltering.as_view(), name='commandments_filtering'),
    path('mitzvah/<int:pk>', views.MitzvahPage.as_view(), name='mitzvah_details'),
]

mycommandments/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('commandments_app.urls')),
    path('account_app/', include('account_app.urls')),
]

templates/partials/footer.html
<footer class="page-footer font-small bg-dark fixed-bottom">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3" id="footer">© 2020 Copyright: My Commandments
  </div>
  <!-- Copyright -->

</footer>

templates/partials/messages.html
{% if messages %}
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
{% endif %}

templates/partials/navbar_homepage.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'commandments_app:index' %}"><i class="fas fa-book-reader"> My Commandments</i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'commandments_app:homepage' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'commandments_app:all_commandments' %}">All Commandments</a>
            </li>
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account_app:profile' %}">Profile ({{ user.username }})</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account_app:logout' %}">Logout</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item active">
                <span>You are not logged into the website, Go back to <a href="{% url 'commandments_app:index' %}">Homepage</a></span>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

templates/partials/navbar_index.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'commandments_app:index' %}"><i class="fas fa-book-reader"> My Commandments</i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item active">
              <a class="nav-link"href="{% url 'commandments_app:about' %}">About us</a>
          </li>
          <li class="nav-item active">
              <a class="nav-link"href="{% url 'commandments_app:faq' %}">FAQ</a>
          </li>
      </ul>

      <ul class="navbar-nav">
        {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'commandments_app:homepage' %}">Homepage</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account_app:logout' %}">Logout</a>
            </li>
        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'account_app:signup' %}">Sign Up</a>
          </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account_app:login' %}">Login</a>
            </li>
        {% endif %}
      </ul>
  </div>
</nav>