account_app/urls.py
from django.urls import path
from account_app import views

app_name = 'account_app'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile')
]

commandments_app/urls.py
from django.urls import path
from commandments_app import views

app_name = 'commandments_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('homepage/', views.homepage, name='homepage'),
    path('all_commandments/', views.all_commandments, name='all_commandments'),
    path('commandments_filtering/', views.CommandmentsFiltering.as_view(), name='commandments_filtering'),
    path('mitzvah/<int:pk>', views.MitzvahPage.as_view(), name='mitzvah_details'),
]

mycommandments/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('commandments_app.urls')),
    path('account_app/', include('account_app.urls')),
]

commandments_app/models.py
from django.db import models

# Create your models here.

commandments_app/forms.py
from django.forms import ModelForm, Select, HiddenInput

from account_app.models import UserFiltering

CHOICES = (('Y','Yes'),('N','No'))
OPTIONS = (('Male','Male'),('Female','Female'))

class PersonalCommandmentsForm(ModelForm):
    class Meta:
        model = UserFiltering
        fields = ['user','live_in_israel','kohen','not_a_vegetarian','judge','farmer','married','children','employer','lend','sorcery','gender']
        widgets = {
            'user': HiddenInput(),
            'live_in_israel': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'kohen': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'not_a_vegetarian': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'judge': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'farmer': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'married': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'children': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'employer': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'lend': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'sorcery': Select(choices=CHOICES, attrs={'class': 'form-control w-75', }),
            'gender': Select(choices=OPTIONS, attrs={'class': 'form-control w-75', }),
        }

commandments_app/views.py
import operator
from functools import reduce

from django.db.models import Q
from django.shortcuts import render
from django.views.generic import DetailView, CreateView
from commandments_app.forms import PersonalCommandmentsForm

from account_app.models import Commandments, UserFiltering

# Create your views here.
from commandments_app.filters import CommandmentsFilter, PersonalFilter, HopmepageFilter


def index(request):
    return render(request, 'commandments_app/index.html')

def about(request):
    return render(request, 'commandments_app/about.html')

def faq(request):
    return render(request, 'commandments_app/faq.html')

class CommandmentsFiltering(CreateView):
    form_class = PersonalCommandmentsForm
    template_name = 'commandments_app/commandments_filtering.html'
    success_url = '/homepage'

    def get_form(self, form_class=None):
        form = super(CommandmentsFiltering, self).get_form(form_class)
        form.fields['user'].initial = self.request.user
        return form


def filter_down(dictionary): # filters out the y answers so the filtering can work properly
    smaller_dict = dict()
    for (key,value) in dictionary.items():
        if value == 'N':
            smaller_dict[key] = 'Y' # for the logic of the db the filter only needs to filter out where the answer in those columns is N
    return smaller_dict


def homepage(request):
    user_info = UserFiltering.objects.get(user=request.user) # finds the user info and gets the answers from the login form
    filter = filter_down(user_info.get_dict())
    commandments = Commandments.objects.filter(Q(**filter) & (Q(gender='Both')|Q(gender=user_info.gender)))  # filters the commandments by the answers to form where the answer was no
    amount = len(commandments)
    page_filter = HopmepageFilter(request.GET, commandments)
    return render(request, 'commandments_app/homepage.html', {'commandments': commandments, 'amount': amount, 'filter': page_filter})

def all_commandments(request):
    commandments = Commandments.objects.all()
    filter = CommandmentsFilter(request.GET, commandments)
    return render(request, 'commandments_app/all_commandments.html', {'commandments': commandments, 'filter': filter})

class MitzvahPage(DetailView):
    model = Commandments
    template_name = 'commandments_app/commandment_details.html'

templates/commandments_app/about.html
{% extends 'base.html' %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/css/about.css" >
{% endblock %}

{% block navbar %}
{% include 'partials/navbar_index.html' %}
{% endblock %}


{% block content %}
<div class="container-fluid" id="over">
    <div class="row justify-content-center align-items-center" id="box">
        <div class="card">
            <div class="card-body" id="text-in-box">
                <p>
                    <strong>About Us</strong><br>
                    MyCommandments.com is an idea launched by a group of friends who<br>
                    felt that the sacrosanct 613 Commandments was a fairly large number<br>
                    to deal with. As such they determined to cut the number down to<br>
                    something more manageable, relevant and personal. The commandments<br>
                    have been organized according to their best understanding of Jewish<br>
                    Orthodox tradition. This site is the result of that effort.<br>
                    Comments, corrections and suggestions are welcome.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/commandments_app/all_commandments.html
{% extends 'base.html' %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/css/homepage.css" >
{% endblock %}

{% block navbar %}
{% include 'partials/navbar_homepage.html' %}
{% endblock %}


{% block content %}
<div class="container-fluid mb-5 mt-3" id="over">

    <h1 id="top-text">All Commandments</h1><hr>
        <form method="get">
            {{ filter.form }}
            <button type="submit">Search</button>
        </form>
    <hr>
    <h3>Total: {{ filter.qs.count }}</h3>
    <div class="row">
        {% for commandment in filter.qs %}
        <div class="col-sm-3">
            <div class="container" style="margin-top: 25px">
                <div class="card">
                    <div class="card-body" id="con-body">
                        Order: {{ commandment.my_order }}<br>
                        Commandment: {{ commandment.mitzvah }}<br>
                        Book: {{ commandment.book }}<br>
                        Parsha: {{ commandment.parsha }}<br>
                        <a class="btn btn-warning" href="{% url 'commandments_app:mitzvah_details' commandment.pk %}">More Info</a>
                        {% if user.is_superuser %}
                            <p>Hello God</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/commandments_app/commandment_details.html
{% extends 'base.html' %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/css/about.css" >
{% endblock %}

{% block navbar %}
{% include 'partials/navbar_homepage.html' %}
{% endblock %}

{% block content %}
<div class="container-fluid" id="over">
    <div class="row justify-content-center align-items-center" id="box">
        <div class="card">
            <div class="card-body" id="text-in-box">
                <h1>Commandment {{ commandments.my_order }}</h1><hr>
                <p>Order in Sefer Ha'Chinuch: <a href="https://www.sefaria.org.il/Sefer_HaChinukh.{{ commandments.chinuch_order }}?lang=en" target="_blank">{{ commandments.chinuch_order }}</a></p>
                <p><strong>Commandment:</strong> {{ commandments.mitzvah }}</p>
                <p><strong>Source:</strong> {{ commandments.book }} ({{ commandments.parsha }}) {{ commandments.chapter }}:{{ commandments.verse }}</p>
                <p><strong>More Details:</strong></p>
                <P>{% if commandments.p_n == "N" %}
                Negative
                {% else %}
                Positive
                {% endif %}Commandment</P>
                <p>Commandment between Man and {{ commandments.man_v }}</p>
                <p>Applicable to
                {% if commandments.gender == "Male" %}
                Men
                {% elif commandments.gender == "Female" %}
                Women
                {% elif commandments.gender == "Both" %}
                Everyone
                {% endif %}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}




{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/commandments_app/commandments_filtering.html
{% extends 'base.html' %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/css/filtering.css" >
{% endblock %}


{% block content %}
<div class="container-fluid mb-5 mt-3" id="over">
    <div class="container w-50 overflow-auto" style="margin-bottom: 70px; margin-top: 70px">
        <div class="card mx-auto">
            <div class="card-body" id="body-of-card">
                <h2>Please Fill Out This Form:</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/commandments_app/faq.html
{% extends 'base.html' %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/css/faq.css" >
{% endblock %}


{% block navbar %}
{% include 'partials/navbar_index.html' %}
{% endblock %}


{% block content %}
<div class="container-fluid" id="over">
    <div class="row justify-content-center align-items-stretch" id="box">
        <div class="col-6">
            <div class="card">
                <div class="card-body" id="text-in-box">
                    <p>
                    <strong>FAQ</strong><br>
                    <br>
                    <strong>Q: What’s wrong with the 613 commandments?</strong>
                    <br>
                    A: Nothing wrong. However, not all of them are applicable in a time without the Temple in Jerusalem.<br>
                    <br>
                    <strong>Q. How many commandments are potentially applicable today?</strong>
                    <br>
                    A: According to the Chafetz Chaim, “The Little Book of Mitzvoth”, a total of 273xxx are applicable today, however the exact total can vary widely depending on the exact circumstances of the individual (hence the creation of this site).<br>
                    <br>
                    <strong>Q: What is the source for your listing of the commandments? I understand there are a number of lists that don’t agree with each other.</strong>
                    <br>
                    A: Our source is the “Sefer Hachinuch”, cross referenced where possible with Maimonides. All authoritative lists agree on a total of 613 Biblical commandments, however it is correct that various authorities have different choices of what the 613 are.<br>
                    <br>
                    <strong>Q: Is it true that some commandments “repeat” themselves?</strong>
                    <br>
                    A: Each commandment makes a particular point, however there are a number of commandments that strongly resemble each other, such as “Don’t desecrate the Sabbath”, and “Keep the Sabbath”. We provide a function to consolidate such parallel commandments.<br>
                    <br>
                    <strong>Q: I find that many commandments that are listed for me are not particularly relevant.</strong>
                    <br>
                    A: That’s fine. You can “hide” it, or make a group of the less relevant ones. (For example people will group all the various commandments on Illicit Relations into one – they got the point).<br>
                    <br>
                    <strong>Q: Are these commandments just for Jews or do they apply to people of other faiths?</strong>
                    <br>
                    A: According to Jewish tradition the 613 commandments (or their derivatives) only apply to Jews. Non-Jews are only obligated in what is known as the 7 Noachide commandments, though many of the other commandments are fairly good advice. It’s recommended that you seek religious guidance within your own faith or tradition.<br>
                    <br>
                    <strong>Q: Am I a bad person if I don’t keep the commandments?</strong>
                    <br>
                    A: Nobody is perfect. We all have our work cut out for us. An idea of the list is to enable a person to prioritize the commandments they want to work on. Good luck.<br>
                    <br>
                    <strong>Q: Are you Rabbis?</strong>
                    <br>
                    A: Some of the contributors have Rabbinic ordination. However this program does not have any formal Rabbinic supervision or approval, though a few thought it was really cool.<br>
                    <br>
                    <strong>Q: What makes you qualified to present this material?</strong>
                    <br>
                    A: Nothing in particular. Read a lot. Asked a lot of questions. We like making lists and no one else was doing anything like this.<br>
                    <br>
                    <strong>Q: This is a great idea. How can we help out?</strong>
                    <br>
                    A: Donations will go a big way. See Support and Participate pages. If you have more ambitious ideas, don’t hesitate to be in touch.<br>
                    <br>
                    <strong>Q: Are you connected or affiliated with any organization?</strong>
                    <br>
                    A: No. But would be happy for some organization to bankroll us.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/commandments_app/homepage.html
{% extends 'base.html' %}

{% block stylesheet %}
<link defer rel="stylesheet" href="/static/css/homepage.css" >
{% endblock %}

{% block navbar %}
{% include 'partials/navbar_homepage.html' %}
{% endblock %}


{% block content %}
<div class="container-fluid mb-5 mt-3" id="over">

    <h1 id="top-text">My Commandments</h1>
    <br>
<!--        <form method="get">-->
<!--            <small class="form-text">Currently, filtering can only work with one filter at a time, further implementation to come</small>-->
<!--            <div class="form-group row">-->
<!--            {{ filter.form.as_p }}-->
<!--            </div>-->
<!--            <div class="form-group row">-->
<!--                <div class="col-sm-10">-->
<!--                    <button type="submit" class="btn btn-primary">Search</button>-->
<!--                </div>-->
<!--            </div>-->
<!--        </form>-->
<!--    <hr>-->
    <h3>Total: {{ filter.qs.count }}</h3>
    <div class="row">
        {% for commandment in filter.qs %}
        <div class="col-lg-3">
            <div class="container" style="margin-top: 25px">
                <div class="card text-center border-dark to-be-rounded">
                    {% if commandment.social and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #9315D8;">
                    {% elif commandment.social and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #5F0491;">
                    {% elif commandment.faith and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #263BDA;">
                    {% elif commandment.faith and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #4C5DE0;">
                    {% elif commandment.ritual and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #0AD3B7;">
                    {% elif commandment.ritual and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #008876;">
                    {% elif commandment.monetary and commandment.p_n == 'P'%}<div class=" to-be-rounded" id="con-body" style="background-color: #FF0C0C;">
                    {% elif commandment.monetary and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #D90000;">
                    {% elif commandment.speech and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #FF710C;">
                    {% elif commandment.speech and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #D95A00;">
                    {% elif commandment.holidays and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #FFFF0C;">
                    {% elif commandment.holidays and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #D9D900;">
                    {% elif commandment.food and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #A9F70C;">
                    {% elif commandment.food and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #87CB00;">
                    {% elif commandment.criminal and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #0BE70B;">
                    {% elif commandment.criminal and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #00AE00;">
                    {% elif commandment.intimacy and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #E80B88;">
                    {% elif commandment.intimacy and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #AE0063;">
                    {% elif commandment.idolatry and commandment.p_n == 'P'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #FFBC0C;">
                    {% elif commandment.idolatry and commandment.p_n == 'N'%}<div class="card-body to-be-rounded" id="con-body" style="background-color: #D99D00;">
                    {% else %}<div class="card-body to-be-rounded" id="con-body">
                    {% endif %}
                        {{ commandment.mitzvah }}<br>
                        <a class="btn btn-warning" href="{% url 'commandments_app:mitzvah_details' commandment.pk %}">More Info</a>
                        {% if user.is_superuser %}
                            <p>Hello God</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/commandments_app/index.html
{% extends 'base.html' %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/css/index.css" >
{% endblock %}

{% block navbar %}
{% include 'partials/navbar_index.html' %}
{% endblock %}


{% block content %}
<div class="container-fluid" id="over">
    <div class="row justify-content-center align-items-center" id="big-text">
        <div class="col-6">
            <h1 id="main-text">Welcome to <br>My Commandments</h1><br>
            {% if not user.is_authenticated %}
            <a class="btn btn-primary btn-lg" href="{% url 'account_app:signup' %}">Sign Up</a>
            <a class="btn btn-primary btn-lg" href="{% url 'account_app:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/commandments_app/update.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'partials/navbar_homepage.html' %}
{% endblock %}

{% block content %}
<div class="container w-50 overflow-auto" style="margin-bottom: 70px; margin-top: 70px">
    <div class="card mx-auto">
        <div class="card-body">
            {% if 'updatefilm' in request.path %}
            <h3>Update a Film</h3>
            {% elif 'update_director' in request.path %}
            <h3>Update Director</h3>
            {% elif 'addfilm' in request.path %}
            <h3>Add a Film</h3>
            {% else %}
            <h3>Add a Director</h3>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {% if 'updatefilm' in request.path %}
                <button type="submit" class="btn btn-primary">Update Film</button>
                {% elif 'update_director' in request.path %}
                <button type="submit" class="btn btn-primary">Update Director</button>
                {% elif 'addfilm' in request.path %}
                <button type="submit" class="btn btn-primary">Add Film</button>
                {% else %}
                <button type="submit" class="btn btn-primary">Add Director</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}